### ISSUE TITLE
mythx report cli layout

### ISSUE THREAD

**Issue by Miller-kk** [dmuhs/mythx-cli#11]
* MythX CLI version: v1.4.36.4
* Python version: v3.6.8
* Operating System: Ubuntu 18.04.3 LTS

### Description

As you can see in the picture below, the codeline information and nicely created tables in pythx are gone. If these aren't there, can I work on the pull-request?

<img width="1430" alt="스크린샷 2019-09-28 오후 7 57 33" src="https://user-images.githubusercontent.com/25917847/65815428-45db1400-e22a-11e9-8b13-8942e224dfa6.png">

### What I Did
I used the following command.

```
mythx report b05ce253-962c-4fee-b2ef-b8a426d9f792
```

**Comment by dmuhs** [comment]
Check out the latest version on `master` :slightly_smiling_face: I have been working to get things into `mythx-cli`. I hope to pack a next release `0.2` in the coming week. That will include the tables as default format and a couple of bugfixes. :+1:

**Comment by Miller-kk** [comment]
Thank you @dmuhs :)

I would like to ask one more question. When the current output type is json, the format given by the server of mythx is given as it is. Isn't it nice to make the json output type like report (line, swc, severity, description)? If it's good, I want to contribute this part to the pull request.

I think pythx and mythx-cli are very helpful tools today. So I want to make a lot of things using these tools.

Below is a screenshot of the output in json form.

<img width="1430" alt="스크린샷 2019-09-28 오후 7 57 33" src="https://user-images.githubusercontent.com/25917847/65844221-4b427680-e370-11e9-9d29-648c75f74149.png">

**Comment by dmuhs** [comment]
I totally agree regarding the report format. There are already quite a few use cases that require the API response *as is*, so we shouldn't break these integrations. However, having a better report format would greatly simplify some of the formatter code and enable new cool output formats.

Maybe a good way to solve this issue would be to provide an additional helper function in `mythx_cli.formatter.util` that takes a `DetectedIssuesResponse` and an `AnalysisInputResponse` (similar to the other formatters) and outputs a dict according to the better report format. This dict can then be used by the other formatters to do their pretty-printing. A common issue is that we need the issues to be grouped by file and sorted by line number descending. One thing to note here is that in this better report format, we have to preserve the important but yet unused data from the `extra` field in the issues and `meta` field in the reports.

@Miller-kk Does that make sense? And do you already have a concrete idea for a better JSON format?

**Comment by Miller-kk** [comment]
Thank you for the good answer :)

I understand. I don't have a good idea for JSON format yet. However, I thought it was cumbersome to hardcode mythx_cli.formatter.util separately to convert the source map into a line of source code in JSON format. So I think it would be nice to have an additional feature that can extract these simple JSON formats separately.

continue looking at the source code to find out what we can contribute.

Thank you very much 👍

**Comment by dmuhs** [comment]
Found some time yesterday and decided to take a step back on this issue. The API already returns decoded locations if source code has been submitted. I have updated the `pythx` and `mythx-models` dependencies to pick up this field and make it accessible in the domain models.
So without intervention in the actual CLI code, using the latest version, if you run something like `mythx --format=json-pretty analyze my-file.sol` you should see the decoded locations in the JSON.

I will take a good hard look at the formatters I have implemented so far and refactor them to use the decoded locations from the new model, and if resolution is not possible, I will resort to something like a bytecode offset (e.g. if the user ran a bytecode-only analysis).

**Comment by dmuhs** [comment]
The new format indexed by file is now available to all formatter classes and the rendering routines. The latest release v0.6.20 should fix the data structure concerns. :+1:
