### ISSUE TITLE
Option to sort finding by type (even across multiple files)

### ISSUE THREAD

**Issue by maurelian** [dmuhs/mythx-cli#158]
- MythX CLI version: 0.6.16
- Python version: 3.7.5
- Operating System: Catalina
- 

### Description

I would like to be able to request output sorted by SWC title. This would mean that all findings of a certain type would go together. 

This would be useful because sometimes I suspect there might be reentrancy somewhere, and just want to review all instances of that possible vuln.

**Comment by maurelian** [comment]
This will be particularly useful for detectors that identify common, simple anti-patterns like "use eternal vs internal", "pin pragma", and "unused variables", "hard-coded gas", etc.

**Comment by dmuhs** [comment]
Fixed in #198 and scheduled for the next release :+1:

**Comment by dmuhs** [comment]
This is out in v0.6.20 now :tada: Consider this documentation section for a short sample: https://mythx-cli.readthedocs.io/en/latest/usage.html#fetching-analysis-reports
