### ISSUE TITLE
Unsupported macOS version

### ISSUE THREAD

**Issue by maurelian** [dmuhs/mythx-cli#34]
* MythX CLI version: 0.2.1
* Python version: 3.7.5
* Operating System: 10.15.1 Catalina 

### Description
```
mythx analyze --mode quick contracts/**/*.sol
Unsupported macOS version.
We only support Mavericks, Yosemite, El Capitan, Sierra, High Sierra and Mojave.
Usage: mythx analyze [OPTIONS] [TARGET]...

Error: Error installing solc version v0.5.10: Command '['sh', '/var/folders/vk/01zl87497jx6bq66fhhhd9zm0000gn/T/py-solc-x-tmp/solidity_0.5.10/scripts/install_deps.sh']' returned non-zero exit status 1.
```

**Comment by dmuhs** [comment]
This is an issue with the [py-solc-x](https://github.com/iamdefinitelyahuman/py-solc-x) dependency. Could you open up the issue there? I'll notify the developers that I can also make a PR to add support if necessary :+1:

**Comment by dmuhs** [comment]
Bumped to the latest `py-solc-x` version in `mythx-cli==0.5.3`. The changes from https://github.com/iamdefinitelyahuman/py-solc-x/issues/26 are in now. :+1:

**Comment by mds1** [comment]
I'm currently getting the same issue:

```text
mythx analyze contracts/ContractName.sol
Unsupported macOS version.
We only support Mavericks, Yosemite, El Capitan, Sierra, High Sierra and Mojave.
WARNING:solcx:Command '['sh', '/var/folders/12/7t1jw7md6tl7l0bn5k7qm3fc0000gn/T/solcx-tmp-66983/so
lidity_0.5.0/scripts/install_deps.sh']' returned non-zero exit status 1.
```

Using
- Python version: 3.7.7
- Operating System: 10.15.1 Catalina

Below is the output from `mythx version`

```text
╒═════════╤══════════════════════════════════╕
│ Api     │ v1.6.0                           │
├─────────┼──────────────────────────────────┤
│ Maru    │ 0.7.4                            │
├─────────┼──────────────────────────────────┤
│ Mythril │ 0.22.1                           │
├─────────┼──────────────────────────────────┤
│ Harvey  │ 0.0.41                           │
├─────────┼──────────────────────────────────┤
│ Hash    │ df2ac71c075a98d70dddb7d0a30b9f79 │
╘═════════╧══════════════════════════════════╛
```

However, it does seem like things are currently running. Current status is `[ 82%] Building CXX object test/CMakeFiles/soltest.dir/libsolidity/AnalysisFramework.cpp.o`.

From [this comment](https://github.com/iamdefinitelyahuman/py-solc-x/issues/26#issuecomment-567169571) in the issue created by @maurelian, it seems this is actually a warning that can be ignored. However, that's not clear from the error message so I'm not totally sure if everything is running as expected.
