### ISSUE TITLE
What's the right way to pass in bytecode?

### ISSUE THREAD

**Issue by maurelian** [dmuhs/mythx-cli#6]
* MythX CLI version: latest
* Python version: sufficient
* Operating System: macos

### Description

I'm trying to process creation bytecode. 

### What I Did

I saved the bytecode to a file call Token.bin. 
I tried running `mythx analyze --mode quick --async Token.bin`.
No luck. 
I tried:
`cat Whitelist.bin | mythx analyze --mode quick --async /dev/stdin`
and `cat Whitelist.bin | mythx analyze --mode quick --async`

What eventually worked was: 
`mythx analyze --mode quick --async \`cat Whitelist.bin\``
which seems kind of odd.

**Comment by dmuhs** [comment]
`mythx` by default does not support stdin to pass parameters. That makes detection a bit harder. What you can do however is use `xargs`, which ships with all common Linux distros and MacOS:

```
cat foo.bin | xargs mythx analyze
```
It will basically take each line of the file and add it as a parameter to the specified command. You can also use this to fetch the reports of multiple UUIDs as outlined in the usage docs: https://mythx-cli.readthedocs.io/en/latest/usage.html#asynchronous-analysis

Let me know if this helps :slightly_smiling_face:

**Comment by maurelian** [comment]
Yep, xargs works for me.
