### ISSUE TITLE
Feature request: Automatically convert analysis IDs to lowercase

### ISSUE THREAD

**Issue by b-mueller** [dmuhs/mythx-cli#94]
* MythX CLI version: 0.6.5
* Python version: 3.7.4
* Operating System: Mac

### Description

Convert analysis IDs to lowercase automatically. The dashboard shows IDs uppercase which means copy/pasting them into a "render" command doesn't work:

```
mythx render --markdown 0D07D850-7114-40C2-A544-8CF09E77DA84
Fetching report for analysis 0D07D850-7114-40C2-A544-8CF09E77DA84
The API returned an error:
Got unexpected status code 404: {"status":404,"error":"Analysis not found"}
```

**Comment by dmuhs** [comment]
Fixed in https://github.com/dmuhs/mythx-cli/pull/100. Now all render targets are converted to lowercase automatically before querying the API :+1:
